name: Build and Test

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - uses: actions/checkout@v2

    - name: Build
      run: go build .

    - name: Test
      run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.ref == ‘refs/heads/master’ && github.event_name == ‘push’ }}
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: almarkdev/chargers-service
        build-args: DBpw_arg=${{ secrets.DB_PW }}
        tag_with_ref: true
